name: auth
description: auth
version: 1.2.0+8
homepage: https://vinbrain.net
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  dotted_border: ^2.0.0
  file_picker: ^4.0.2
  flutter_rating_bar: ^4.0.0
  image_picker: ^0.8.4
  shimmer: ^2.0.0
  webview_flutter: ^2.0.12
  open_file: ^3.2.1
  overlay_support: ^1.2.1
  image: ^3.0.8
  crop_image: ^1.0.1
  connectivity: ^3.0.6
  expandable_page_view: ^1.0.6
  camera: ^0.9.4+11
  cloud_firestore: ^3.1.14
  device_info_plus: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.2
  freezed: ^0.14.5
  json_annotation: ^4.1.0
  json_serializable: ^5.0.0
  pedantic: ^1.11.1
  intl_utils: ^2.4.0
  injectable_generator: ^1.5.2

flutter:
  uses-material-design: true
  assets:
    - assets/